title: "drawing"
description: "A browser-based drawing tool."
baseurl: "/drawing"
url: "https://europanite.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
highlighter: rouge